server:
  port: 8101
  servlet:
    context-path: /api
spring:
  application:
    name: wx-gallery-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wx_gallery
    username: root
    password: wx123456

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 不使用驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 仅在开发环境打印日志
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    # 分组配置
    group:
      default:
#        group-name: 默认分组   // 去除后，可直接访问 http://localhost:8101/api/v2/api-docs
        api-rule: package
        api-rule-resources:
          - com.wolf.wxgallerybackend.controller